.TH TSH "Northwestern University EECS 343" "NU EECS 343 - Operating Systems - tiny shell"
.SH NAME
tsh \- A tiny shell
.SH SYNOPSIS
.B tsh
.SH DESCRIPTION
.B 
tiny shell (tsh) is a simple linux shell program written by C. It can execute 7 built in commands, which are:
.IP exit 
--
Quit tsh

.IP cd new_directory 
--
Changes the current operating directory to the new_directory.

.IP jobs 
--
Show process id and job id of currently active jobs

.IP bg jobid 
--
Send SIGCONT to a background job, restart it.  

.IP fg jobid  
--
Switch a background job to foreground

.IP alias string
--
Alias command specified by the string

.IP unalias string
--
Unalias command specified by the string

.SH DESIGN APPROACH
The project development was driven by the testcases and handout. 
In the ths.c the skelton already port the signal catcher, and we implement the
"sig" function in response to the signals received. 

In the runtime.c, it mainly deal with executing the command (fork, execv, and wait), and maintaining a linked list to
store each jobs. We maintain a global variable fgpid to track the current fg process status. For the wait command, we did a sleep loop constatnly checking the status of the fgpid. Once the SIGHILD
signal generated, the signal handler call the waitpid() function to check the new status of the process and update job
linked list and fgpid. Before the shell process next command, the CheckJobs() function check the job list, 
list any DONE processes before removing it.    

We implemented Redirect IO and Alias toward extra credit. 

.SH AUTHOR
Yu Zhou,
Chao Feng
